### ISSUE TITLE
Matrix calculus

### ISSUE THREAD

**Issue by notEvil** [sgsokol/Deriv#20]
Hi,

I made a few changes to _Deriv.R_ so that matrix operations like `%*%`, `det` and `solve` work.

Please take a look at my fork, and in particular
https://github.com/notEvil/Deriv/blob/master/showcase.R

Its a proof of concept and certainly needs adjustment to be considered for a pull request.

KR, Andreas

**Comment by sgsokol** [comment]
Hi,
Thank you for your proposal. I find your ideas interesting and probably of general interest.
Do I understand right that 'x' in %*%, det and solve is still considered as a scalar value and not a vector neither matrix?
Three days ago I have released v3.9.0 and just pushed it on github, so could you prepare a PR based on this version so that I could check it in my environment?
Thanks,
Serguei.

**Comment by notEvil** [comment]
Yes, the variable 'x' is always assumed to be a scalar.

I just merged your branch into my fork and showcase.R still works. I'll create the pull request shortly (even though, as I said, its certainly not ready for pull)

**Comment by sgsokol** [comment]
Finally, I've got a frame to see PR #21 a little closer and play a bit around so I have few remarks.
1. I found cool your trick with `.derivative` but in its current state, it works only for the first argument and replaces only the first rule entry. It is not general enough. It can be helpful in other places so I plan to work on its generalization. I'll keep you informed when it's ready.
2. The current rule for `matrix()` can fail if `nrow` and `ncol` are omitted: `Deriv(~matrix(c(x,x)))` gives `matrix(c(1, 1), nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL)` which clearly has wrong dimensions. It's not your fault. I have just to figure out how the use of default values can be fixed. They cannot be just omitted as in other parts of `drule` table they are already in use, e.g. for `log()`.
Again, I'll keep you informed.
3. You don't have to use `deCache()` in your tests to avoid the cache-ing. Just add `cache.exp=FALSE` (or `ca=F` for short form) to `Deriv()` call.
4. Your rule for `qnorm()` is written only for default values of `lower.tail` and `log.p`. For completeness, all cases of these parameters should be treated or otherwise not treated cases should be signaled as not working.

**Comment by notEvil** [comment]
Thanks!

regarding 1: this is probably the hardest part, which is why I used this hack

regarding 2: there is a comment in `showcase.R` ^^ I guess this one is easy, because its a special behavior of matrix (ignoring default parameters). In case this is a language feature, well, maybe its not worth the trouble

regarding 3: thanks

regarding 4: thats not true. The rule contains the corresponding variables which are substituted by Deriv.

**Comment by sgsokol** [comment]
I have pushed a new branch test_matcalc which resolves p. 1 and 2. from previous remarks. You are welcome to test it. Your copula example from showcase.R produces the same numbers.

As to p.4, when I compare your result with numerical differentiation I have significant difference for `lower.tail=FALSE`. See :
```
library(numDeriv)
p=0.1; mu=1; 
eval(Deriv(~qnorm(p, mu, lower.tail=FALSE), "p")) # 5.69806
eval(Deriv(~qnorm(p, mu, lower.tail=TRUE), "p")) # 5.69806, i.e the same (!)
ff=function(p) qnorm(p, mu, lower.tail=FALSE);
ft=function(p) qnorm(p, mu, lower.tail=TRUE);
numDeriv::grad(ff, p) # -5.69806
numDeriv::grad(ft, p) # 5.69806, the sign is opposite, which is normal.
```
So I still think the rule for `qnorm` must take into account different values of `lower.tail` and probably `log.p` (not yet tested).

**Comment by notEvil** [comment]
You were obviously right about p.4, the following should be correct

    .qnorm_derivatives = list(p=quote(1/dnorm(qnorm(p, mean=mean, sd=sd, lower.tail=lower.tail, log.p=log.p), mean=mean, sd=sd) * (if (log.p) exp(p) else 1) * if (lower.tail) 1 else -1),
                              mean=quote(1),
                              sd=quote((qnorm(p, mean=mean, sd=sd, lower.tail=lower.tail, log.p=log.p) - mean)/sd))
    
    assign('qnorm', .qnorm_derivatives, envir=Deriv::drule)
    
    
    show = function(expression) {
      derivative = Deriv::Deriv(expression, 'x')
      print(derivative)
      #print(Deriv::Simplify(.))
    }
    
    show(quote(qnorm(x)))
    show(quote(qnorm(x, log.p=T)))
    show(quote(qnorm(x, lower.tail=F)))
    show(quote(qnorm(x, lower.tail=F, log.p=T)))
    
    
    test = function(expression, x) {
      result = eval(Deriv::Deriv(expression, 'x'))
      
      function_ = as.function(c(alist(x=), list(expression)))
      expected_result = numDeriv::grad(function_, x)
      
      print(all.equal(result, expected_result))
    }
    
    test(quote(qnorm(x, mean=1.2, sd=2.3)), 0.7)
    test(quote(qnorm(x, mean=1.2, sd=2.3, lower.tail=F)), 1 - 0.7)
    test(quote(qnorm(x, mean=1.2, sd=2.3, log.p=T)), log(0.7))
    test(quote(qnorm(x, mean=1.2, sd=2.3, lower.tail=F, log.p=T)), log(1 - 0.7))
    
    test(quote(qnorm(0.7,          mean=x, sd=2.3)), 1.2)
    test(quote(qnorm(1 - 0.7,      mean=x, sd=2.3, lower.tail=F)), 1.2)
    test(quote(qnorm(log(0.7),     mean=x, sd=2.3, log.p=T)), 1.2)
    test(quote(qnorm(log(1 - 0.7), mean=x, sd=2.3, lower.tail=F, log.p=T)), 1.2)
    
    test(quote(qnorm(0.7,          mean=1.2, sd=x)), 2.3)
    test(quote(qnorm(1 - 0.7,      mean=1.2, sd=x, lower.tail=F)), 2.3)
    test(quote(qnorm(log(0.7),     mean=1.2, sd=x, log.p=T)), 2.3)
    test(quote(qnorm(log(1 - 0.7), mean=1.2, sd=x, lower.tail=F, log.p=T)), 2.3)

I can confirm that your solution works for my showcase. Great work btw!

Did you consider `diagonal` and `identity_matrix`? They would get rid of the `if` in derivatives of `diag` (and functions based on it like trace).

**Comment by sgsokol** [comment]
Thanks for testing and `qnorm()` rule updating. Now, all numeric tests run well on all arguments (not only `p`) with any combination of `lower.tail` and `log.p`

As far as I understand, `diagonal()` and `identity_matrix()` are just proxies to `diag()` so for working in general case they need the same tests on their argument. Btw, I had to fix `diag()` rule for a case when x is a scalar but `nrow` or `ncol` are set. In any case, as they are not standard R functions, I think the right place for their rules is in the user's space not in the package.

I guess this new feature takes shape now. I will prepare a new 4.0 version for submitting to CRAN (in around 2 weeks, not before). In my opinion, you should be credited as a contributor. Is it OK for you? If yes, could you send me your formal record (first name, last name and email) that you would like to see in Authors field of the DESCRIPTION file.

**Comment by notEvil** [comment]
Sure, if you think my contribution is worth it. You find my details at https://cran.r-project.org/web/packages/docopulae/index.html.

Regarding `diag`, a static expression in drule doesn't work in this case. Maybe extend drule to allow functions which resolve to an expression?

**Comment by sgsokol** [comment]
In which case "static expression in drule doesn't work"?

**Comment by notEvil** [comment]
I was referring to nrow and ncol being missing and therefore not of much use in drule. Your solution using Simplify is pretty neat though! Probably better than introducing functions.

**Comment by notEvil** [comment]
https://github.com/sgsokol/Deriv/blob/5c4f4d52a62e649dad8be881db144a0879adc73b/R/Deriv.R#L383 doesn't work for `Deriv(quote(a[['b']]), 'x')` because `st == 0[['b']]` which can't be simplified (Simplify tries to eval it because everything is conuloch). I suggest to check result of `Deriv_` on previous line and return 0.

Other than that, the new version is pretty stable.

**Comment by sgsokol** [comment]
On its way to CRAN v4.0
