### ISSUE TITLE
support for genetic functions?

### ISSUE THREAD

**Issue by alibool** [sgsokol/Deriv#22]
```
# works well
Deriv(function(x, y) (x+y)/2)
# fail, as mean is a genetic function, and mean.numeric is invisible
Deriv(function(x, y) mean(c(x, y)))
```

**Comment by sgsokol** [comment]
You mean "generic", right? What do you expect the derivate of `mean(x, y)` by `x` should be? Remember that `x` can be a vector. Remember also that `y` in this writing is interpreted as `trim` parameter (cf. `?mean`)

**Comment by sgsokol** [comment]
> What do you expect the derivate of `mean(x, y)` by `x` should be?

Oops, I read too fast and missed `c(x,y)` in your writing which invalidates my remark about the `trim` parameter. However, the question about "what the derivate should be" is still valid.

**Comment by alibool** [comment]
Suppose x, y are both scalar, `mean(c(x, y))` is equal to `(x + y) / 2`, while the latter one is a valid input for `Deriv`, the former one is not.

**Comment by sgsokol** [comment]
A supposition that `x` and `y` are scalars is a very strong one. As we (Deriv authors and contributors) are supposed to provide a general solution, we cannot bind ourselves and our users to such supposition.
However, if the formula `(x+y)/2` is sufficient for your needs, you can incapsulate it in a function and add that function to your personal table of differentiation rules (cf. ?Deriv, a note about `drule` and example "Custom differentiation rule")

**Comment by alibool** [comment]
Thanks for your reply. BTW, does 'Deriv' support vector input? such as `function(x) sum(x)`, when `x=c(1, 2)`, return `c(1, 1)`, when `x=c(2, 3, 4)`, return `c(1, 1, 1)`.

**Comment by sgsokol** [comment]
Yes and ... no. Yes for classic vector functions where operations are done term by term and vector form is preserved, e.g. `sum(x^2)` gives `sum(2*x)` where `x` can perfectly be a vector. No for the case of `sum()` you point. As `Deriv(~sum(x), "x")` gives `sum(1)` which is simplified to plain `1` which is bad but for the moment I don't see the right general solution.
You could be tempted to replace `mean(x)` by `sum(x)/length(x)` and derivate the latter expression but the problem is a possible `na.rm` parameter for `mean()` and `sum()` and `NA`s in `x` as they can have an impact on `length(x)`.
